name: CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.py'
      - '**.yml'
      - '**.toml'
  push:
    branches:
      - main
    paths:
      - '**.py'
      - '**.yml'
      - '**.toml'

jobs:
  ruff:
    name: Ruff check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: chartboost/ruff-action@v1
      with:
        args: 'format --check'
    - uses: chartboost/ruff-action@v1
